package Hibernate;
// Generated 29-oct-2015 12:48:33 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AlbaranEntrada generated by hbm2java
 */
public class AlbaranEntrada  implements java.io.Serializable {


     private Integer id;
     private String numeroAlbaran;
     private String numeroPedido;
     private Date fecha;
     private int proveedorId;

    public AlbaranEntrada() {
    }

    public AlbaranEntrada(String numeroAlbaran, String numeroPedido, Date fecha, int proveedorId) {
       this.numeroAlbaran = numeroAlbaran;
       this.numeroPedido = numeroPedido;
       this.fecha = fecha;
       this.proveedorId = proveedorId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNumeroAlbaran() {
        return this.numeroAlbaran;
    }
    
    public void setNumeroAlbaran(String numeroAlbaran) {
        this.numeroAlbaran = numeroAlbaran;
    }
    public String getNumeroPedido() {
        return this.numeroPedido;
    }
    
    public void setNumeroPedido(String numeroPedido) {
        this.numeroPedido = numeroPedido;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getProveedorId() {
        return this.proveedorId;
    }
    
    public void setProveedorId(int proveedorId) {
        this.proveedorId = proveedorId;
    }




}


