package Hibernate;
// Generated 23-oct-2015 10:33:54 by Hibernate Tools 4.3.1



/**
 * DestinosProductos generated by hbm2java
 */
public class DestinosProductos  implements java.io.Serializable {


     private Integer id;
     private int destinoId;
     private int productoId;

    public DestinosProductos() {
    }

    public DestinosProductos(int destinoId, int productoId) {
       this.destinoId = destinoId;
       this.productoId = productoId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getDestinoId() {
        return this.destinoId;
    }
    
    public void setDestinoId(int destinoId) {
        this.destinoId = destinoId;
    }
    public int getProductoId() {
        return this.productoId;
    }
    
    public void setProductoId(int productoId) {
        this.productoId = productoId;
    }




}


