package Hibernate;
// Generated 20-oct-2015 11:47:51 by Hibernate Tools 4.3.1



/**
 * Historial generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


     private Integer id;
     private boolean accion;
     private String referencia;
     private int cantidad;

    public Historial() {
    }

    public Historial(boolean accion, String referencia, int cantidad) {
       this.accion = accion;
       this.referencia = referencia;
       this.cantidad = cantidad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public boolean isAccion() {
        return this.accion;
    }
    
    public void setAccion(boolean accion) {
        this.accion = accion;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


