package Hibernate;
// Generated 20-oct-2015 11:47:51 by Hibernate Tools 4.3.1



/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer id;
     private String referencia;
     private float longitud;
     private int peso;
     private int stock;

    public Producto() {
    }

    public Producto(String referencia, float longitud, int peso, int stock) {
       this.referencia = referencia;
       this.longitud = longitud;
       this.peso = peso;
       this.stock = stock;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public float getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(float longitud) {
        this.longitud = longitud;
    }
    public int getPeso() {
        return this.peso;
    }
    
    public void setPeso(int peso) {
        this.peso = peso;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }




}


