package Hibernate;
// Generated 23-oct-2015 10:33:54 by Hibernate Tools 4.3.1



/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer id;
     private String referencia;
     private String refIrizar;
     private int proveedorId;
     private String descripcion;
     private int longitud;
     private String acabado;
     private int unidades;
     private String imagen;

    public Producto() {
    }

    public Producto(String referencia, String refIrizar, int proveedorId, String descripcion, int longitud, String acabado, int unidades, String imagen) {
       this.referencia = referencia;
       this.refIrizar = refIrizar;
       this.proveedorId = proveedorId;
       this.descripcion = descripcion;
       this.longitud = longitud;
       this.acabado = acabado;
       this.unidades = unidades;
       this.imagen = imagen;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getRefIrizar() {
        return this.refIrizar;
    }
    
    public void setRefIrizar(String refIrizar) {
        this.refIrizar = refIrizar;
    }
    public int getProveedorId() {
        return this.proveedorId;
    }
    
    public void setProveedorId(int proveedorId) {
        this.proveedorId = proveedorId;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(int longitud) {
        this.longitud = longitud;
    }
    public String getAcabado() {
        return this.acabado;
    }
    
    public void setAcabado(String acabado) {
        this.acabado = acabado;
    }
    public int getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(int unidades) {
        this.unidades = unidades;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }




}


